version: '2'
services:
  acmedns:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/linuxgemini/acme-dns:maintenance
    ports:
      - "443:443"
      - "53:53"
      - "53:53/udp"
      - "80:80"
    volumes:
      - ./config:/etc/acme-dns:ro
      - ./data:/var/lib/acme-dns
