name: golangci-lint
concurrency: ci-${{ github.ref }}

on:
  push:
    tags:
      - v*
    branches:
      - maintenance
  pull_request:
  schedule:
    # Run every 12 hours, at the 15 minute mark. E.g.
    # 2020-11-29 00:15:00 UTC, 2020-11-29 12:15:00 UTC, 2020-11-30 00:15:00 UTC
    - cron:  "15 */12 * * *"

jobs:
  golangci:
    name: Lint Sourcecode
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          check-latest: true
          go-version: ">=1.18.0"

      - run: go version

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          args: --timeout=3m
